"""Pydantic data contracts shared across the verification pipeline.

The new pipeline needs a unified schema that can be safely passed between the
five stages.  Each model mirrors the JSON contracts in the specification.
To help future contributors, the field-level semantics are kept identical to
the written brief and extra fields are explicitly forbidden.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Claim(BaseModel):
    """Quantitative claim produced by Stage A and consumed by later stages."""

    model_config = ConfigDict(extra="forbid")

    id: str
    sentence_id: str
    text: str
    is_statistic: bool
    kind: Literal["statistic", "ratio", "range", "relative_change", "rate_per", "delta"]
    values: list[dict] | None = None  # [{"value": float, "unit": str}]
    time: str | None = None
    comparison_time: str | None = None
    geo: str | None = None
    population: str | None = None
    span: dict  # {"start": int, "end": int}
    verbatim: str | None = None
    canonical: dict | None = None  # {"unit": str, "value_norm": float, ...}


class EvidenceSpan(BaseModel):
    """Text or table snippet retrieved during Stage B."""

    model_config = ConfigDict(extra="forbid")

    doc_id: str
    page: int | None = None
    start: int | None = None
    end: int | None = None
    content: str
    provenance: dict | None = None  # {"section": str|None, "table": str|None}
    scores: dict | None = None  # {"bm25": float|None, "dense": float|None, "num_match": int|None}


class VerificationResult(BaseModel):
    """Judge decision emitted by Stage C."""

    model_config = ConfigDict(extra="forbid")

    claim_id: str
    label: Literal["supported", "contradicted", "insufficient", "outdated", "computed-mismatch", "disputed"]
    unit_ok: bool | None = None
    time_ok: bool | None = None
    population_ok: bool | None = None
    matched_value: float | None = None
    expected_value: float | None = None
    numeric_distance: float | None = None
    chosen_evidence: list[dict] = Field(
        default_factory=list
    )  # [{"doc_id": str, "page": int|None, "start": int|None, "end": int|None}]
    rationale_short: str | None = None


class Score(BaseModel):
    """Calibrated score generated by Stage D."""

    model_config = ConfigDict(extra="forbid")

    claim_id: str
    prob_supported: float
    score_0_100: int
    uncertainty: dict | None = None  # {"std": float|None}
    factors: dict | None = None  # {"evidence_strength": float, ...}


__all__ = ["Claim", "EvidenceSpan", "VerificationResult", "Score"]
